runtime: python27
api_version: 1
threadsafe: true

runtime_config:
  python_version: 3

libraries:
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"

# Handlers define how to route requests to your application.
handlers:

- url: /favicon\.ico
  mime_type: image/x-icon
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /(.*\.png)
  mime_type: image/png
  static_files: static/\1
  upload: static/(.*\.png)

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
      
- url: /(.*\.html)
  mime_type: text/html
  static_files: templates/\1
  upload: templates/(.*\.html)
  
- url: /
  static_files: templates/index.html
  upload: templates/index.html
  
- url: /.* # This regex directs all routes to main.app
  script: main.app
 
  
# [START env_variables]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    # mysql://[username]:[password]@/[SQLinstanceName]?unix_socket=/cloudsql/[connectionName]
    # connectName will be something like project1:us-central1:instance1
    SQLALCHEMY_DATABASE_URI: >-
      mysql://ctdb1:750111@35.201.139.171/company?unix_socket=/cloudsql/jt-erp:asia-east1:ctdb1
      # mysql://ctdb1:750111@104.155.195.75/company?unix_socket=/cloudsql/ct-erp:asia-east1:ctdb1
# [END env_variables]

beta_settings:
    # replace with your connectionName [project1:us-central1:instance1]
    cloud_sql_instances: jt-erp:asia-east1:ctdb1
